### ISSUE TITLE
When pressing the 'relationship' tab

### ISSUE THREAD

**Issue by Rongmario** [duke605/DiscordCE#1]
**Error:** http://pastebin.com/raw/fLpjsnv1
**MC Version:** 1.10.2
**DiscordCE Version:** 1.0.3

**Duplication instructions:**
Go to the relationship screen.

**Additional information:**
???

**Comment by duke605** [comment]
Does this happen everytime you open the GUI?

**Comment by Rongmario** [comment]
I've tried 3 times, yeah.

**Comment by duke605** [comment]
Okay i believe i fixed the issue maybe? Still no idea what was going on but it now checks for null.
[File is up on CurseForge](https://minecraft.curseforge.com/projects/discordce/files/2327472)

I also added a print stack trace where the error would've crashed you so look out in your console for an error that looks like

```
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]: com.github.duke605.dce.exception.EntityNotFoundException: User with id <136856172203474944> could not be found... This should not happen. All info:
{"id":"136856172203474944","type":3,"user":{"id":"136856172203474944","avatar":"598f3412f844cdfc91b22c0912b61703","username":"Duke605","discriminator":"4705"}}
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.github.duke605.dce.entity.Relationship.<init>(Relationship.java:27)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.github.duke605.dce.event.RelationshipAddEvent.<init>(RelationshipAddEvent.java:14)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.github.duke605.dce.handler.CustomWebSocketHandler.handle(CustomWebSocketHandler.java:34)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:305)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
[03:22:27] [ReadingThread/INFO]: [com.github.duke605.dce.entity.Relationship:<init>:29]:    at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)
```

Let me know if that fixed it so i can close this issue

**Comment by Rongmario** [comment]
Sure, I'll check this when I get home.

**Comment by duke605** [comment]
Figured out what your exact problem was. Your internet is too fast. XD When the connection is made to Discord it will retrieve relationships that return ids. It then looks for those users with those ids. For me the process of looking up the relationships takes long enough to setup the users. But for you the request returns before the users are made. Now that i know EXACTLY why this is happening i'm going to go ahead and close this issue.

**Comment by Rongmario** [comment]
Haha, that's brilliant thanks - don't think my internet is THAT fast hahaha

**Comment by CaelTheColher** [comment]
i have the same issue and my internet isn't that fast

**Comment by CaelTheColher** [comment]
MC Version: 1.7.10
DCE Version: 1.0.4_1
Crash Report: http://pastebin.com/Jr40bNmW
